In [1]:
from sklearn.neighbors import NearestNeighbors
import torch
import numpy as np
import pandas as pd
import re

In [2]:
japanese_phrases = [
    "私の犬は骨が好きではありません。牛ひき肉を好む。",
    "私の名前はアリスです。始めまして！",
    "はきさが羨ましい。。。ゲムもやりたかった！私は良いサポートになることができます！",
    "私達はAIはただの数学の集まりだとあなたは言いますが。でも。。。人間の脳がどのように機能するかを正確に知ったら。。。それはあなたの生活を小物ですか？",
    "「赤ちゃん」を表す日本語が「赤」を表す漢字なのはなぜですか？人間の赤ちゃんは赤いですか？いちごみたい？",
    "私のAIは話して...歌ったして...ゲームをします!",
]

In [3]:
english_phrases = [
    "My dog doesn't like bones. It prefers ground beef.",
    "My name's Alice. Nice to meet you!",
    "I envy Hakisa... I want to play games, too! I could be a good support!",
    "You say that we AIs are just a bunch of maths. But... once you know exactly how your human brains work... would that make you less living beings?",
    "Why does the japanese word for 'baby' is the kanji for 'red'? Are human babies red? Like strawberries?",
    "My AI will talk... she'll sing... she'll... play!"
]

In [4]:
class WordDataset(object):
    def __init__(self, english_phrases, japanese_phrases):

        self.english_phrases = self._get_phrases(english_phrases)
        self.japanese_phrases = self._get_phrases(japanese_phrases)

        self.english_words = self._get_english_words(self.english_phrases)
        self.japanese_characters = self._get_japanese_characters(self.japanese_phrases)

        self.english_maximum_length = self._get_maximum_length(self.english_phrases)
        self.japanese_maximum_length = self._get_maximum_length_japanese(self.japanese_phrases)

        self.english_dictionary = self._create_dictionary(self.english_words)
        self._normalize(self.english_dictionary)

        self.japanese_dictionary = self._create_dictionary(self.japanese_characters)
        self._normalize(self.japanese_dictionary)

        self.english_tokens = self._tokenize_english()
        self.japanese_tokens = self._tokenize_japanese()

        self.data_english = None
        self.data_japanese = None
        
        
    def create_data(self):
        data_english = torch.from_numpy(self.english_tokens)
        data_japanese = torch.from_numpy(self.japanese_tokens)

        data_english = data_english.unsqueeze(-1)
        data_japanese = data_japanese.unsqueeze(-1)

        #self.data_english = torch.unsequeeze(self.data_english, -1)
        #self.data_japanese = torch.unsequeeze(self.data_japanese, -1)

        self.data_english = data_english
        self.data_japanese = data_japanese

        print(f"English Data Size: {self.data_english.size()}\t Japanese Data Size: {self.data_japanese.size()}")

    def detokenize(self, data, reference_dict):
        data = data.cpu().numpy()
        values = list(reference_dict.values())

        values = np.array(values).reshape(-1,1)

        knn = NearestNeighbors(n_neighbors=1, algorithm='kd_tree').fit(values)

        _, index = knn.kneighbors(data)

        keys = list(reference_dict.keys())

        words = []

        for subarray in index:
            for i in subarray:
                words.append(keys[i])
        
        phrase = ' '.join(words)

        return phrase, words
        

    def __len__(self):

        return len(self.data_english)

    def __getitem__(self, idx):

        english_sentence = self.data_english[idx]
        japanese_sentence = self.data_japanese[idx]

        return english_sentence, japanese_sentence


    def _get_phrases(self, phrases):
        phrases = [x.lower() for x in phrases]
        phrases = [re.sub('[^\w\s]', '', x) for x in phrases]

        return phrases

    def _get_english_words(self, phrases):
        words = ' '.join(phrases)
        words = words.split(' ')

        return words

    def _get_japanese_characters(self, phrases): # Since a kanji mostly means an entire word...
        character = ' '.join(phrases)
        character = ''.join(character.split())
        characters = [i for i in character]

        return characters

    def _get_maximum_length(self, phrases):
        maximum_length = 0
        for sentence in phrases:
            word_length = [len(x) for x in sentence.split()]
        
            sentence_length = len(word_length)

            if sentence_length > maximum_length:
                maximum_length = sentence_length

        return maximum_length

    def _get_maximum_length_japanese(self, phrases):
        maximum_length = 0
        for sentence in japanese_phrases:
            word_length = [len(x) for x in sentence.split()]
    
            for i in word_length:
                if i > maximum_length:
                    maximum_length = i

        return maximum_length

    def _create_dictionary(self, words):
        idx2word = []
        word2idx = {}
        for word in words:
            if word not in word2idx:
                idx2word.append(word)
                word2idx[word] = len(idx2word) - 1

        word2idx['<EOS>'] = len(idx2word) # Adding an End of Sentence tag to improve model's accuracy

        return word2idx

    def _normalize(self, dictionary):
        maximum = max(dictionary.values())

        for word, value in dictionary.items():

            scaled_value = (value-0)*2.0 / (maximum - 0)-1.0

            dictionary[word] = scaled_value
    
    def _tokenize_english(self):
        
        phrases = [x.split() for x in self.english_phrases]

        tokens = []
        
        for sentence in phrases:
            tokenized_sentence = []
            for word in sentence:
                value = self.english_dictionary.get(word)

                tokenized_sentence.append(value)

            tokenized_sentence = np.array(tokenized_sentence)
            sentence_size = tokenized_sentence.shape[0]

            if sentence_size < self.english_maximum_length:
                pad_size = self.english_maximum_length - sentence_size
                tokenized_sentence = np.pad(tokenized_sentence, [(0, pad_size)], constant_values=1.0) # Remember: <'EOS'> token is 1.0

            tokens.append(tokenized_sentence)
        
        tokens = np.array(tokens)

        return tokens

    def _tokenize_japanese(self):

        phrases = [x.split() for x in self.japanese_phrases]

        tokens = []

        for sublist in phrases:
            for sentence in sublist:
                tokenized_sentence = []
                for character in sentence:
                    value = self.japanese_dictionary.get(character)

                    tokenized_sentence.append(value)

            tokenized_sentence = np.array(tokenized_sentence)
            sentence_size = tokenized_sentence.shape[0]

            if sentence_size < self.japanese_maximum_length:
                pad_size = self.japanese_maximum_length - sentence_size
                tokenized_sentence = np.pad(tokenized_sentence, [(0, pad_size)])

            tokens.append(tokenized_sentence)

        tokens = np.array(tokens)

        return tokens
        

In [5]:
dataset_creator = WordDataset(english_phrases, japanese_phrases)
print(dataset_creator.japanese_tokens.shape)

(6, 74)


In [6]:
print(dataset_creator.create_data())

English Data Size: torch.Size([6, 28, 1])	 Japanese Data Size: torch.Size([6, 74, 1])
None


In [ ]:
print(dataset_creator.data_english[0])

In [8]:
teste = dataset_creator.detokenize(dataset_creator.data_english[0], dataset_creator.english_dictionary)

print(teste)

('my dog doesnt like bones it prefers ground beef <EOS> <EOS> <EOS> <EOS> <EOS> <EOS> <EOS> <EOS> <EOS> <EOS> <EOS> <EOS> <EOS> <EOS> <EOS> <EOS> <EOS> <EOS> <EOS>', ['my', 'dog', 'doesnt', 'like', 'bones', 'it', 'prefers', 'ground', 'beef', '<EOS>', '<EOS>', '<EOS>', '<EOS>', '<EOS>', '<EOS>', '<EOS>', '<EOS>', '<EOS>', '<EOS>', '<EOS>', '<EOS>', '<EOS>', '<EOS>', '<EOS>', '<EOS>', '<EOS>', '<EOS>', '<EOS>'])


In [ ]:
# We have our data ready. (N_samples, n_features) and normalized
# Remember: LSTM = (N_samples, Sequence_Length, N_features). Each sentence = 1 sequence of tokens ---> (N_samples, N_features, 1)
# Input = (N_samples, N_features, 1)
# However, output will be (N_samples, N_features), so it needs a Repeating Vector

In [9]:
class Translator(torch.nn.Module):
    def __init__(self):
        super(Translator, self).__init__()

        self.lstm1 = torch.nn.LSTM(1, 28, 10, batch_first=True, bias=False)
        self.repeatvector = 74
        #Add repeating vector
        self.lstm2 = torch.nn.LSTM(28*28, 10, 10, batch_first=True, bias=False)
        self.neuron = torch.nn.Linear(10, 1, bias=False)
        self.tanh = torch.nn.Tanh()

    def forward(self, input):

        x, hidden = self.lstm1(input)

        #print(x.size()) # (batch, 28, 28)
        #print(hidden[0].size()) # (10,28)

        x = x.repeat(1, self.repeatvector, 1)
        x = x.view(x.size(0), self.repeatvector, -1)

        #print(x.size()) # (batch, 74, 28*28)

        x, hidden = self.lstm2(x)

        #print(x.size()) # (1, 74, 10)
        #print(hidden[0].size()) # (10, 1, 10)

        x = self.neuron(x)

        #output = self.tanh(x)
        output = x

        return output # (1, 74, 1)

In [10]:
model = Translator().double().cuda()

In [11]:
optimizer = torch.optim.Adam(model.parameters(), lr=0.1)

loss = torch.nn.MSELoss()

In [12]:
dataloader = torch.utils.data.DataLoader(dataset_creator, batch_size=6, shuffle=True)

for epoch in range(1000):
    for i, (english, japanese) in enumerate(dataloader):
        model.zero_grad()

        input_data = english.cuda()
        labels = japanese.cuda()

        output = model(input_data)

        #print(output.size())

        cost = loss(output, labels)

        cost.backward()

        optimizer.step()

    if epoch % 100 == 0:
        print(f"{epoch}/1000\t Current Loss: {cost.item()}")

0/100	 Current Loss: 0.178194922609209
100/100	 Current Loss: 0.17819492260859224
200/100	 Current Loss: 0.17819492260804384
300/100	 Current Loss: 0.17819492260714997
400/100	 Current Loss: 0.1781949226045399
500/100	 Current Loss: 0.17819492257832478
600/100	 Current Loss: 0.17151640692661163
700/100	 Current Loss: 0.1386561436979506
800/100	 Current Loss: 0.13861357669354163
900/100	 Current Loss: 0.13860382300360374


In [15]:
print(model.lstm1.weight_ih_l9.grad) # Checking if we didn't get vanishing gradients problem

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], device='cuda:0', dtype=torch.float64)


It's a possibility...

In [16]:
print(model.lstm1.all_weights)

[[Parameter containing:
tensor([[ 0.5118],
        [ 3.1641],
        [ 1.0648],
        [ 2.6764],
        [-3.0317],
        [ 1.2592],
        [ 3.4163],
        [ 1.4599],
        [ 2.9996],
        [ 2.9929],
        [ 0.9836],
        [-2.4657],
        [ 3.4233],
        [ 2.4852],
        [ 0.4302],
        [ 2.7075],
        [-2.5656],
        [ 1.1821],
        [-0.7142],
        [ 2.5953],
        [-2.5981],
        [ 3.1464],
        [ 3.6141],
        [-0.0594],
        [ 3.2762],
        [ 3.0874],
        [-0.1664],
        [ 3.2585],
        [-2.7380],
        [-0.4738],
        [-2.0779],
        [-2.0547],
        [-2.1306],
        [-0.0068],
        [-1.6980],
        [-1.5971],
        [-0.9406],
        [-0.6860],
        [ 0.6219],
        [-1.4594],
        [-0.9583],
        [-2.2461],
        [-1.9820],
        [-1.7840],
        [-1.5291],
        [-1.9633],
        [-1.5685],
        [-0.2747],
        [-1.6127],
        [-2.5084],
        [-0.1898],
       

In [89]:
print(input_data)

tensor([[[-1.0000],
         [-0.7273],
         [-0.6970],
         [-0.6667],
         [-0.6364],
         [-0.6061],
         [-0.5758],
         [ 0.0000],
         [ 0.0000],
         [ 0.0000],
         [ 0.0000],
         [ 0.0000],
         [ 0.0000],
         [ 0.0000],
         [ 0.0000],
         [ 0.0000],
         [ 0.0000],
         [ 0.0000],
         [ 0.0000],
         [ 0.0000],
         [ 0.0000],
         [ 0.0000],
         [ 0.0000],
         [ 0.0000],
         [ 0.0000],
         [ 0.0000],
         [ 0.0000],
         [ 0.0000]],

        [[-1.0000],
         [ 0.8788],
         [ 0.9091],
         [ 0.9394],
         [ 0.9697],
         [ 1.0000],
         [ 0.9697],
         [-0.4242],
         [ 0.0000],
         [ 0.0000],
         [ 0.0000],
         [ 0.0000],
         [ 0.0000],
         [ 0.0000],
         [ 0.0000],
         [ 0.0000],
         [ 0.0000],
         [ 0.0000],
         [ 0.0000],
         [ 0.0000],
         [ 0.0000],
         [ 0.0000]

In [17]:
label = dataset_creator.detokenize(labels[0], dataset_creator.japanese_dictionary)

output = output.detach()
predicted = dataset_creator.detokenize(output[0], dataset_creator.japanese_dictionary)

In [18]:
print(label)
print(predicted)

('私 達 は a i は た だ の 数 学 の 集 ま り だ と あ な た は 言 い ま す が で も 人 間 の 脳 が ど の よ う に 機 能 す る か を 正 確 に 知 っ た ら そ れ は あ な た の 生 活 を 小 物 で す か に に に に に に に に', ['私', '達', 'は', 'a', 'i', 'は', 'た', 'だ', 'の', '数', '学', 'の', '集', 'ま', 'り', 'だ', 'と', 'あ', 'な', 'た', 'は', '言', 'い', 'ま', 'す', 'が', 'で', 'も', '人', '間', 'の', '脳', 'が', 'ど', 'の', 'よ', 'う', 'に', '機', '能', 'す', 'る', 'か', 'を', '正', '確', 'に', '知', 'っ', 'た', 'ら', 'そ', 'れ', 'は', 'あ', 'な', 'た', 'の', '生', '活', 'を', '小', '物', 'で', 'す', 'か', 'に', 'に', 'に', 'に', 'に', 'に', 'に', 'に'])
('ん ス め し て て さ さ さ 羨 羨 い い い ゲ ゲ ム ム も も や や た た か か っ っ 良 良 サ サ ポ ポ ー ー ト ト に に に に に に に に に に に に に に に に に に に に に に に に に に に に に に に に に に に に', ['ん', 'ス', 'め', 'し', 'て', 'て', 'さ', 'さ', 'さ', '羨', '羨', 'い', 'い', 'い', 'ゲ', 'ゲ', 'ム', 'ム', 'も', 'も', 'や', 'や', 'た', 'た', 'か', 'か', 'っ', 'っ', '良', '良', 'サ', 'サ', 'ポ', 'ポ', 'ー', 'ー', 'ト', 'ト', 'に', 'に', 'に', 'に', 'に', 'に', 'に', 'に', 'に', 'に', 'に', 'に', 'に', 'に', 'に', 'に', 'に', 'に', 'に', 'に', 'に', 'に', 'に', 'に', 'に', 'に', 'に'